### ISSUE TITLE
Angular V18.1.3 SSR: ERROR ReferenceError: document is not defined at _NgIcon.setSvg

### ISSUE THREAD

**Issue by BladiCreator** [ng-icons/ng-icons#131]
When I run the Angular app with SSR, an error appears indicating that the instance of document is not used correctly.

**To Reproduce**
1. Generate an Angular SSR project.
2. Install ng-icons (look at the dependencies installed below).
3. Use any icon in **app.component.html**.
4. Run `ng serve`.

**Expected behavior**
The document should be instantiated correctly, and no flickering should occur on the page to avoid content layout shifts.

**Screenshots**
![image](https://github.com/user-attachments/assets/1367e622-f36a-467b-8054-e4e3c188a3e3)

**Packages (please complete the following information):**
 - "@ng-icons/core": "^29.2.0",
 - "@ng-icons/font-awesome": "^29.2.0",
 - "@ng-icons/simple-icons": "^29.2.0",
 - "@ng-icons/tabler-icons": "^29.2.0",
 - "@angular/common": "^18.1.3",

**Comment by ashley-hunter** [comment]
Hi, thank you for the report! I will get a fix for this released later today, thank you!

**Comment by ashley-hunter** [comment]
Thanks for the feedback, this should now be resolved. Any further issues please let me know, thank you!

**Comment by BladiCreator** [comment]
After upgrading to the last version with the fix of this issue, now there is SVG duplication occurring inside the ng-icon tag, caused by inserting SVG in both the server side and the browser side:
We can show duplication of SVG tags:
![image](https://github.com/user-attachments/assets/8b13393d-84e4-4f6b-92fb-77ad1ab72dd8)
If I disable overflow hidden, we can see both SVGs:
![image](https://github.com/user-attachments/assets/dd668a0d-9f25-4bca-b1f7-6b7648b09053)

**Comment by ashley-hunter** [comment]
Interesting, I'll re-open this issue and get a fix for this, thanks for letting me know

**Comment by ashley-hunter** [comment]
This should now be resolved in v29.2.2 - any further issues just let me know! Thanks!

**Comment by BladiCreator** [comment]
Duplicate icons continue to appear in SSR
    "@ng-icons/core": "^29.2.0",
    "@ng-icons/font-awesome": "^29.2.0",
    "@ng-icons/simple-icons": "^29.2.0",
    "@ng-icons/tabler-icons": "^29.2.0",
    
To simulate:
![image](https://github.com/user-attachments/assets/51a33ac5-3e29-4b0f-bda2-baf2ef103fb1)
![image](https://github.com/user-attachments/assets/05955dcb-6a8b-4d12-bff6-cdcc387b0c31)
![image](https://github.com/user-attachments/assets/d7c1eb81-1db8-4436-8871-dd8911e6fc19)
![image](https://github.com/user-attachments/assets/3adb328f-8395-4c1f-95dc-93ef379f43ba)

**Comment by ashley-hunter** [comment]
Thanks @BladiCreator , could you verify the exact version you are using, this should have been resolved in 29.2.2 - as you are using "^29.2.0" this may or may not be using a version with a fix in it. You could try updating to the latest v29.4.0 release to see if this issue is still occurring.

**Comment by BladiCreator** [comment]
I updated to:
    "@ng-icons/core": "^29.4.0",
    "@ng-icons/font-awesome": "^29.4.0",
    "@ng-icons/simple-icons": "^29.4.0",
    "@ng-icons/tabler-icons": "^29.4.0",
The bug is still present.
![image](https://github.com/user-attachments/assets/3b209bcb-05bc-4bbc-ad71-280cfca31527)

**Comment by ashley-hunter** [comment]
This should now be resolved in the 29.5.0 release - any issues just let me know, thank you for your help!
